### ISSUE TITLE
Erros when compiling with GCC 7.8.1

### ISSUE THREAD

**Issue by sergei-dyshel** [MaskRay/ccls#94]
I'm building `ccls` on CentOS7 with GCC 7 (complete build flow as in #87). After rebasing to current version I'm getting the following compilation error:
(I guess it has something to do with e8317bd)
```
[  2%] Building CXX object CMakeFiles/ccls.dir/src/clang_complete.cc.o
/home/sergei/src/ccls/src/clang_complete.cc:87:38: error: template argument 1 is invalid
   llvm::StringMap<ErrorOr<vfs::Status>> Cache;
                                      ^~
/home/sergei/src/ccls/src/clang_complete.cc:87:41: error: template argument 1 is invalid
   llvm::StringMap<ErrorOr<vfs::Status>> Cache;
                                         ^~~~~
/home/sergei/src/ccls/src/clang_complete.cc:89:46: error: template argument 1 is invalid
   void Update(Twine Path, ErrorOr<vfs::Status> S) {
                                              ^
/home/sergei/src/ccls/src/clang_complete.cc:89:46: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:89:46: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:89:46: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:89:27: error: invalid template-id
   void Update(Twine Path, ErrorOr<vfs::Status> S) {
                           ^~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:89:35: error: reference to ‘vfs’ is ambiguous
   void Update(Twine Path, ErrorOr<vfs::Status> S) {
                                   ^~~
In file included from /home/sergei/src/ccls/src/clang_complete.hh:18:0,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/src/ccls/src/clang_tu.hh:28:27: note: candidates are: namespace llvm::vfs = clang::clang::vfs;
 namespace vfs = clang::vfs;
                           ^
In file included from /home/sergei/opt/clang/include/clang/Basic/FileManager.h:19:0,
                 from /home/sergei/src/ccls/src/clang_tu.hh:21,
                 from /home/sergei/src/ccls/src/clang_complete.hh:18,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/opt/clang/include/clang/Basic/VirtualFileSystem.h:46:11: note:                 namespace clang::vfs { }
 namespace vfs {
           ^~~
/home/sergei/src/ccls/src/clang_complete.cc:89:48: error: ‘auto’ parameter not permitted in this context
   void Update(Twine Path, ErrorOr<vfs::Status> S) {
                                                ^
/home/sergei/src/ccls/src/clang_complete.cc:93:37: error: template argument 1 is invalid
   IntrusiveRefCntPtr<vfs::FileSystem>
                                     ^
/home/sergei/src/ccls/src/clang_complete.cc:94:46: error: template argument 1 is invalid
   Producer(IntrusiveRefCntPtr<vfs::FileSystem> FS) {
                                              ^
/home/sergei/src/ccls/src/clang_complete.cc:94:46: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:94:46: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:94:46: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:94:12: error: invalid template-id
   Producer(IntrusiveRefCntPtr<vfs::FileSystem> FS) {
            ^~~~~~~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:94:31: error: reference to ‘vfs’ is ambiguous
   Producer(IntrusiveRefCntPtr<vfs::FileSystem> FS) {
                               ^~~
In file included from /home/sergei/src/ccls/src/clang_complete.hh:18:0,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/src/ccls/src/clang_tu.hh:28:27: note: candidates are: namespace llvm::vfs = clang::clang::vfs;
 namespace vfs = clang::vfs;
                           ^
In file included from /home/sergei/opt/clang/include/clang/Basic/FileManager.h:19:0,
                 from /home/sergei/src/ccls/src/clang_tu.hh:21,
                 from /home/sergei/src/ccls/src/clang_complete.hh:18,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/opt/clang/include/clang/Basic/VirtualFileSystem.h:46:11: note:                 namespace clang::vfs { }
 namespace vfs {
           ^~~
/home/sergei/src/ccls/src/clang_complete.cc:94:48: error: ‘auto’ parameter not permitted in this context
   Producer(IntrusiveRefCntPtr<vfs::FileSystem> FS) {
                                                ^~
/home/sergei/src/ccls/src/clang_complete.cc: In member function ‘void ccls::PreambleStatCache::Update(llvm::Twine)’:
/home/sergei/src/ccls/src/clang_complete.cc:90:5: error: ‘Cache’ was not declared in this scope
     Cache.try_emplace(Path.str(), std::move(S));
     ^~~~~
/home/sergei/src/ccls/src/clang_complete.cc:90:5: note: suggested alternative: ‘Matcher’
     Cache.try_emplace(Path.str(), std::move(S));
     ^~~~~
     Matcher
/home/sergei/src/ccls/src/clang_complete.cc:90:45: error: ‘S’ was not declared in this scope
     Cache.try_emplace(Path.str(), std::move(S));
                                             ^
/home/sergei/src/ccls/src/clang_complete.cc: In member function ‘int ccls::PreambleStatCache::Producer()’:
/home/sergei/src/ccls/src/clang_complete.cc:95:18: error: reference to ‘vfs’ is ambiguous
     struct VFS : vfs::ProxyFileSystem {
                  ^~~
In file included from /home/sergei/src/ccls/src/clang_complete.hh:18:0,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/src/ccls/src/clang_tu.hh:28:27: note: candidates are: namespace llvm::vfs = clang::clang::vfs;
 namespace vfs = clang::vfs;
                           ^
In file included from /home/sergei/opt/clang/include/clang/Basic/FileManager.h:19:0,
                 from /home/sergei/src/ccls/src/clang_tu.hh:21,
                 from /home/sergei/src/ccls/src/clang_complete.hh:18,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/opt/clang/include/clang/Basic/VirtualFileSystem.h:46:11: note:                 namespace clang::vfs { }
 namespace vfs {
           ^~~
/home/sergei/src/ccls/src/clang_complete.cc:95:23: error: expected ‘{’ before ‘ProxyFileSystem’
     struct VFS : vfs::ProxyFileSystem {
                       ^~~~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:96:25: error: expected primary-expression before ‘&’ token
       PreambleStatCache &Cache;
                         ^
/home/sergei/src/ccls/src/clang_complete.cc:96:26: error: ‘Cache’ was not declared in this scope
       PreambleStatCache &Cache;
                          ^~~~~
/home/sergei/src/ccls/src/clang_complete.cc:96:26: note: suggested alternative: ‘Matcher’
       PreambleStatCache &Cache;
                          ^~~~~
                          Matcher
/home/sergei/src/ccls/src/clang_complete.cc:96:31: error: expected ‘}’ before ‘;’ token
       PreambleStatCache &Cache;
                               ^
/home/sergei/src/ccls/src/clang_complete.cc:98:45: error: template argument 1 is invalid
       VFS(IntrusiveRefCntPtr<vfs::FileSystem> FS, PreambleStatCache &Cache)
                                             ^
/home/sergei/src/ccls/src/clang_complete.cc:98:75: error: invalid use of incomplete type ‘struct ccls::PreambleStatCache::Producer()::VFS’
       VFS(IntrusiveRefCntPtr<vfs::FileSystem> FS, PreambleStatCache &Cache)
                                                                           ^
/home/sergei/src/ccls/src/clang_complete.cc:95:12: note: forward declaration of ‘struct ccls::PreambleStatCache::Producer()::VFS’
     struct VFS : vfs::ProxyFileSystem {
            ^~~
/home/sergei/src/ccls/src/clang_complete.cc:98:10: error: expected primary-expression before ‘(’ token
       VFS(IntrusiveRefCntPtr<vfs::FileSystem> FS, PreambleStatCache &Cache)
          ^
/home/sergei/src/ccls/src/clang_complete.cc:98:69: error: expected primary-expression before ‘&’ token
       VFS(IntrusiveRefCntPtr<vfs::FileSystem> FS, PreambleStatCache &Cache)
                                                                     ^
/home/sergei/src/ccls/src/clang_complete.cc:100:46: error: template argument 1 is invalid
       llvm::ErrorOr<std::unique_ptr<vfs::File>>
                                              ^~
/home/sergei/src/ccls/src/clang_complete.cc:100:46: error: template argument 2 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:101:42: error: template argument 1 is invalid
       openFileForRead(const Twine &Path) override {
                                          ^~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:108:32: error: template argument 1 is invalid
       llvm::ErrorOr<vfs::Status> status(const Twine &Path) override {
                                ^
/home/sergei/src/ccls/src/clang_complete.cc:108:69: error: a function-definition is not allowed here before ‘{’ token
       llvm::ErrorOr<vfs::Status> status(const Twine &Path) override {
                                                                     ^
/home/sergei/src/ccls/src/clang_complete.cc:95:23: warning: unused variable ‘ProxyFileSystem’ [-Wunused-variable]
     struct VFS : vfs::ProxyFileSystem {
                       ^~~~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc: In member function ‘llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem> ccls::PreambleStatCache::Consumer(llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>)’:
/home/sergei/src/ccls/src/clang_complete.cc:124:32: error: template argument 1 is invalid
       llvm::ErrorOr<vfs::Status> status(const Twine &Path) override {
                                ^
/home/sergei/src/ccls/src/clang_complete.cc:124:34: error: conflicting return type specified for ‘virtual int ccls::PreambleStatCache::Consumer(llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>)::VFS::status(const llvm::Twine&)’
       llvm::ErrorOr<vfs::Status> status(const Twine &Path) override {
                                  ^~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:45:25: error:   overriding ‘virtual llvm::ErrorOr<clang::vfs::Status> clang::vfs::ProxyFileSystem::status(const llvm::Twine&)’
   llvm::ErrorOr<Status> status(const Twine &Path) override {
                         ^~~~~~
/home/sergei/src/ccls/src/clang_complete.cc: In member function ‘virtual int ccls::PreambleStatCache::Consumer(llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>)::VFS::status(const llvm::Twine&)’:
/home/sergei/src/ccls/src/clang_complete.cc:125:24: error: ‘const struct ccls::PreambleStatCache’ has no member named ‘Cache’
         auto I = Cache.Cache.find(Path.str());
                        ^~~~~
/home/sergei/src/ccls/src/clang_complete.cc:126:24: error: ‘const struct ccls::PreambleStatCache’ has no member named ‘Cache’
         if (I != Cache.Cache.end())
                        ^~~~~
/home/sergei/src/ccls/src/clang_complete.cc:128:45: error: cannot convert ‘llvm::ErrorOr<clang::vfs::Status>’ to ‘int’ in return
         return getUnderlyingFS().status(Path);
                                             ^
/home/sergei/src/ccls/src/clang_complete.cc: At global scope:
/home/sergei/src/ccls/src/clang_complete.cc:274:39: error: template argument 1 is invalid
     IntrusiveRefCntPtr<vfs::FileSystem> FS, DiagnosticConsumer &DC,
                                       ^
/home/sergei/src/ccls/src/clang_complete.cc:274:39: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:274:39: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:274:39: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:274:5: error: invalid template-id
     IntrusiveRefCntPtr<vfs::FileSystem> FS, DiagnosticConsumer &DC,
     ^~~~~~~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:274:24: error: reference to ‘vfs’ is ambiguous
     IntrusiveRefCntPtr<vfs::FileSystem> FS, DiagnosticConsumer &DC,
                        ^~~
In file included from /home/sergei/src/ccls/src/clang_complete.hh:18:0,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/src/ccls/src/clang_tu.hh:28:27: note: candidates are: namespace llvm::vfs = clang::clang::vfs;
 namespace vfs = clang::vfs;
                           ^
In file included from /home/sergei/opt/clang/include/clang/Basic/FileManager.h:19:0,
                 from /home/sergei/src/ccls/src/clang_tu.hh:21,
                 from /home/sergei/src/ccls/src/clang_complete.hh:18,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/opt/clang/include/clang/Basic/VirtualFileSystem.h:46:11: note:                 namespace clang::vfs { }
 namespace vfs {
           ^~~
/home/sergei/src/ccls/src/clang_complete.cc:274:41: error: ‘auto’ parameter not permitted in this context
     IntrusiveRefCntPtr<vfs::FileSystem> FS, DiagnosticConsumer &DC,
                                         ^~
/home/sergei/src/ccls/src/clang_complete.cc: In function ‘std::unique_ptr<clang::CompilerInstance> ccls::{anonymous}::BuildCompilerInstance(ccls::CompletionSession&, std::unique_ptr<clang::CompilerInvocation>, clang::DiagnosticConsumer&, const ccls::PreambleData*, const WorkingFiles::Snapshot&, std::vector<std::unique_ptr<llvm::MemoryBuffer> >&)’:
/home/sergei/src/ccls/src/clang_complete.cc:284:48: error: ‘FS’ was not declared in this scope
       preamble->Preamble.OverridePreamble(*CI, FS, Bufs.back().get());
                                                ^~
/home/sergei/src/ccls/src/clang_complete.cc:296:31: error: ‘FS’ was not declared in this scope
   Clang->setVirtualFileSystem(FS);
                               ^~
/home/sergei/src/ccls/src/clang_complete.cc: At global scope:
/home/sergei/src/ccls/src/clang_complete.cc:322:54: error: template argument 1 is invalid
                    IntrusiveRefCntPtr<vfs::FileSystem> FS,
                                                      ^
/home/sergei/src/ccls/src/clang_complete.cc:322:54: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:322:54: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:322:54: error: template argument 1 is invalid
/home/sergei/src/ccls/src/clang_complete.cc:322:20: error: invalid template-id
                    IntrusiveRefCntPtr<vfs::FileSystem> FS,
                    ^~~~~~~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:322:39: error: reference to ‘vfs’ is ambiguous
                    IntrusiveRefCntPtr<vfs::FileSystem> FS,
                                       ^~~
In file included from /home/sergei/src/ccls/src/clang_complete.hh:18:0,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/src/ccls/src/clang_tu.hh:28:27: note: candidates are: namespace llvm::vfs = clang::clang::vfs;
 namespace vfs = clang::vfs;
                           ^
In file included from /home/sergei/opt/clang/include/clang/Basic/FileManager.h:19:0,
                 from /home/sergei/src/ccls/src/clang_tu.hh:21,
                 from /home/sergei/src/ccls/src/clang_complete.hh:18,
                 from /home/sergei/src/ccls/src/clang_complete.cc:16:
/home/sergei/opt/clang/include/clang/Basic/VirtualFileSystem.h:46:11: note:                 namespace clang::vfs { }
 namespace vfs {
           ^~~
/home/sergei/src/ccls/src/clang_complete.cc:322:56: error: ‘auto’ parameter not permitted in this context
                    IntrusiveRefCntPtr<vfs::FileSystem> FS,
                                                        ^~
/home/sergei/src/ccls/src/clang_complete.cc: In function ‘void ccls::{anonymous}::BuildPreamble(ccls::CompletionSession&, clang::CompilerInvocation&, const string&, std::unique_ptr<ccls::PreambleStatCache>)’:
/home/sergei/src/ccls/src/clang_complete.cc:330:62: error: ‘FS’ was not declared in this scope
   if (OldP && OldP->Preamble.CanReuse(CI, Buf.get(), Bounds, FS.get()))
                                                              ^~
/home/sergei/src/ccls/src/clang_complete.cc:341:39: error: ‘FS’ was not declared in this scope
           CI, Buf.get(), Bounds, *DE, FS, session.PCH, true, PP)) {
                                       ^~
/home/sergei/src/ccls/src/clang_complete.cc: In function ‘void* ccls::{anonymous}::CompletionPreloadMain(void*)’:
/home/sergei/src/ccls/src/clang_complete.cc:364:39: error: template argument 1 is invalid
     IntrusiveRefCntPtr<vfs::FileSystem> FS = stat_cache->Producer(session->FS);
                                       ^
/home/sergei/src/ccls/src/clang_complete.cc:364:78: error: no matching function for call to ‘ccls::PreambleStatCache::Producer(llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>&)’
     IntrusiveRefCntPtr<vfs::FileSystem> FS = stat_cache->Producer(session->FS);
                                                                              ^
/home/sergei/src/ccls/src/clang_complete.cc:94:3: note: candidate: int ccls::PreambleStatCache::Producer()
   Producer(IntrusiveRefCntPtr<vfs::FileSystem> FS) {
   ^~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc:94:3: note:   candidate expects 0 arguments, 1 provided
/home/sergei/src/ccls/src/clang_complete.cc:366:45: error: could not convert ‘FS’ from ‘int’ to ‘llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>’
             BuildCompilerInvocation(args, FS))
                                             ^
/home/sergei/src/ccls/src/clang_complete.cc:367:75: error: invalid initialization of reference of type ‘const string& {aka const std::basic_string<char>&}’ from expression of type ‘int’
       BuildPreamble(*session, *CI, FS, request.path, std::move(stat_cache));
                                                                           ^
/home/sergei/src/ccls/src/clang_complete.cc:321:6: note: in passing argument 3 of ‘void ccls::{anonymous}::BuildPreamble(ccls::CompletionSession&, clang::CompilerInvocation&, const string&, std::unique_ptr<ccls::PreambleStatCache>)’
 void BuildPreamble(CompletionSession &session, CompilerInvocation &CI,
      ^~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc: In function ‘void* ccls::{anonymous}::CompletionMain(void*)’:
/home/sergei/src/ccls/src/clang_complete.cc:402:39: error: template argument 1 is invalid
     IntrusiveRefCntPtr<vfs::FileSystem> FS =
                                       ^
/home/sergei/src/ccls/src/clang_complete.cc:403:75: error: cannot convert ‘llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>’ to ‘int’ in initialization
         preamble ? preamble->stat_cache->Consumer(session->FS) : session->FS;
                                                                           ^~
/home/sergei/src/ccls/src/clang_complete.cc:405:55: error: could not convert ‘FS’ from ‘int’ to ‘llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>’
         BuildCompilerInvocation(session->file.args, FS);
                                                       ^
/home/sergei/src/ccls/src/clang_complete.cc:421:70: error: invalid initialization of reference of type ‘clang::DiagnosticConsumer&’ from expression of type ‘int’
                                        preamble.get(), snapshot, Bufs);
                                                                      ^
/home/sergei/src/ccls/src/clang_complete.cc:272:35: note: in passing argument 3 of ‘std::unique_ptr<clang::CompilerInstance> ccls::{anonymous}::BuildCompilerInstance(ccls::CompletionSession&, std::unique_ptr<clang::CompilerInvocation>, clang::DiagnosticConsumer&, const ccls::PreambleData*, const WorkingFiles::Snapshot&, std::vector<std::unique_ptr<llvm::MemoryBuffer> >&)’
 std::unique_ptr<CompilerInstance> BuildCompilerInstance(
                                   ^~~~~~~~~~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc: In function ‘void* ccls::{anonymous}::DiagnosticMain(void*)’:
/home/sergei/src/ccls/src/clang_complete.cc:482:39: error: template argument 1 is invalid
     IntrusiveRefCntPtr<vfs::FileSystem> FS =
                                       ^
/home/sergei/src/ccls/src/clang_complete.cc:483:75: error: cannot convert ‘llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>’ to ‘int’ in initialization
         preamble ? preamble->stat_cache->Consumer(session->FS) : session->FS;
                                                                           ^~
/home/sergei/src/ccls/src/clang_complete.cc:485:55: error: could not convert ‘FS’ from ‘int’ to ‘llvm::IntrusiveRefCntPtr<clang::vfs::FileSystem>’
         BuildCompilerInvocation(session->file.args, FS);
                                                       ^
/home/sergei/src/ccls/src/clang_complete.cc:495:70: error: invalid initialization of reference of type ‘clang::DiagnosticConsumer&’ from expression of type ‘int’
                                        preamble.get(), snapshot, Bufs);
                                                                      ^
/home/sergei/src/ccls/src/clang_complete.cc:272:35: note: in passing argument 3 of ‘std::unique_ptr<clang::CompilerInstance> ccls::{anonymous}::BuildCompilerInstance(ccls::CompletionSession&, std::unique_ptr<clang::CompilerInvocation>, clang::DiagnosticConsumer&, const ccls::PreambleData*, const WorkingFiles::Snapshot&, std::vector<std::unique_ptr<llvm::MemoryBuffer> >&)’
 std::unique_ptr<CompilerInstance> BuildCompilerInstance(
                                   ^~~~~~~~~~~~~~~~~~~~~
/home/sergei/src/ccls/src/clang_complete.cc: At global scope:
/home/sergei/src/ccls/src/clang_complete.cc:311:6: warning: ‘bool ccls::{anonymous}::Parse(clang::CompilerInstance&)’ defined but not used [-Wunused-function]
 bool Parse(CompilerInstance &Clang) {
      ^~~~~
make[2]: *** [CMakeFiles/ccls.dir/build.make:76: CMakeFiles/ccls.dir/src/clang_complete.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/ccls.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by sergei-dyshel** [comment]
The problem doesn't reproduce when compiling with GCC 8.

**Comment by MaskRay** [comment]
Thanks for the report. I think it is a [namespace.udir] bug when namespace alias is used, before GCC 8.

```cpp
namespace clang {
    namespace vfs {class A;}
}

namespace llvm {
    namespace vfs = clang::vfs;
}

using namespace clang;
using namespace llvm;

vfs::A x;
```

This fails to compile `error: reference to 'vfs' is ambiguous`.

I have amended the commit by using `llvm::vfs::` instead of `vfs::`
