### ISSUE TITLE
Fail to build with clang 5.0.1

### ISSUE THREAD

**Issue by xuhdev** [MaskRay/ccls#406]
### Observed behavior

```
Building CXX object CMakeFiles/ccls.dir/src/clang_tu.cc.o
/home/hong/src/ccls/src/clang_tu.cc:162:21: error: no member named 'ShortAccum' in 'clang::BuiltinType'
  case BuiltinType::ShortAccum:
       ~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:164:21: error: no member named 'Accum' in 'clang::BuiltinType'
  case BuiltinType::Accum:
       ~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:166:21: error: no member named 'LongAccum' in 'clang::BuiltinType'
  case BuiltinType::LongAccum:
       ~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:168:21: error: no member named 'UShortAccum' in 'clang::BuiltinType'
  case BuiltinType::UShortAccum:
       ~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:170:21: error: no member named 'UAccum' in 'clang::BuiltinType'
  case BuiltinType::UAccum:
       ~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:172:21: error: no member named 'ULongAccum' in 'clang::BuiltinType'
  case BuiltinType::ULongAccum:
       ~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:174:34: error: no member named 'ShortFract' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::ShortFract:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:176:34: error: no member named 'Fract' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::Fract:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:178:34: error: no member named 'LongFract' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::LongFract:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:180:34: error: no member named 'UShortFract' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::UShortFract:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:182:34: error: no member named 'UFract' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::UFract:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:184:34: error: no member named 'ULongFract' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::ULongFract:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:186:34: error: no member named 'SatShortAccum' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::SatShortAccum:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:188:34: error: no member named 'SatAccum' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::SatAccum:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:190:34: error: no member named 'SatLongAccum' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::SatLongAccum:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:192:34: error: no member named 'SatUShortAccum' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::SatUShortAccum:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:194:34: error: no member named 'SatUAccum' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::SatUAccum:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:196:34: error: no member named 'SatULongAccum' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::SatULongAccum:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
/home/hong/src/ccls/src/clang_tu.cc:198:34: error: no member named 'SatShortFract' in 'clang::BuiltinType'
  case BuiltinType::BuiltinType::SatShortFract:
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

### Expected behavior

Sucessful build.

### Steps to reproduce

1. `cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/opt/rh/llvm-toolset-7/root/usr/ -DCMAKE_CXX_COMPILER=clang++`
2. cmake --build Release -j 1

### System information

* ccls version (`git describe --tags --long`):  0.20190314.1-10-gd3808de26ac0
* clang version: 

```
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rh/llvm-toolset-7/root/usr/bin
Found candidate GCC installation: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda, version unknown
```

* OS: RHEL 7.6

**Comment by MaskRay** [comment]
https://github.com/MaskRay/ccls/wiki/Build

> Clang+LLVM headers and libraries, version >= 7 (0.20181225.8 is the last release that supports clang 6)
